version: "3.8"
services:

    db:
      platform: linux/amd64
      image: mysql:5.7
      container_name: mysql_teammanager_docker_symfony
      restart: always
      volumes:
          - db-data:/var/lib/mysql
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      networks:
          - dev

    phpmyadmin:
        image: phpmyadmin:5.0
        platform: linux/amd64
        container_name: phpmyadmin_teammanager_docker_symfony
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: maildev_teammanager_docker_symfony
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8081:80"
        restart: always
        networks:
            - dev

    www:
        build: php
        container_name: www_teammanager_docker_symfony
        ports:
          - "8741:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev

networks:
    dev:

volumes:
    db-data: